name: base_backend
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  mysql1: ^0.20.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

  commons_core:
    path: ./packages/commons/commons-core
